l_korean:
 pm_primary:0 "기본"
 pmg_secondary_building_rye_farm:0 "보조"
 pmg_secondary_building_wheat_farm:0 "보조"
 pmg_secondary_building_rice_farm:0 "보조"
 pmg_secondary_building_maize_farm:0 "보조"
 pmg_secondary_building_millet_farm:0 "보조"
 pm_no_secondary:0 "단일 작물 유지"
 pm_potatoes:0 "감자"
 pm_vineyards:0 "포도원"
 pm_vineyards_building_maize_farm:0 "포도원"
 pm_apple_orchards:0 "사과 과수원"
 pm_citrus_orchards:0 "감귤 과수원"
 pm_fig_orchards:0 "무화과 과수원"
 pm_fig_orchards_building_rice_farm:0 "무화과 과수원"
 pm_mulberry_groves:0 "뽕나무 숲"
 pmg_automation:0 "자동화"
 pmg_automation_building_food_industry:0 "자동화"
 pmg_automation_building_textile_mills:0 "자동화"
 pmg_automation_building_furniture_manufacturies:0 "자동화"
 pmg_automation_building_tooling_workshops:0 "자동화"
 pmg_automation_building_paper_mills:0 "자동화"
 pmg_automation_building_steel_mills:0 "자동화"
 pmg_automation_building_motor_industry:0 "자동화"
 pm_civilian_priority:0 "민간인 우선 순위"
 pm_military_priority:0 "군사 우선 순위"
 pm_craftsman_sewing:0 "수제작"
 pm_sewing_machines:0 "재봉틀 기계"
 pm_electric_sewing_machines:0 "전동 재봉틀 기계"
 pm_traditional_looms:0 "전통 직조기"
 pm_mechanized_looms:0 "기계 직조기"
 pm_automatic_power_looms:0 "자동화 직조기"
 pm_leaded_glass:0 "납 유리"
 pm_manual_glassblowing:0 "수공 유리 제작"
 pm_leblanc_process:0 "레블랑 공정"
 pm_no_explosives_production:0 "비료 생산 우선 시"
 pm_ammonia-soda_process:0 "암모니아 소다 공정"
 pm_vacuum_evaporation:0 "진공 증발"
 pm_brine_electrolysis:0 "염수 전기 분해"
 pmg_fertilizer_production:0 "비료 생산"
 pm_no_artificial_fertilizers:0 "인공 비료 없음"
 pm_artificial_fertilizers:0 "Artificial Fertilizers"
 pm_improved_fertilizer:0 "개선된 비료"
 pm_nitrogen_fixation:0 "질소 고정 처리"
 pm_dyes_production:0 "염료 생산"
 pm_no_synthetic_dyes:0 "합성 염료 없음"
 pmg_synthetic_dyes:0 "합성 염료"
 pm_silk_production:0 "비단 생산"
 pm_no_artificial_fibers:0 "염료 생산 우선 시"
 pm_rayon:0 "인견"
 pm_synthetic_oil:0 "합성유"
 pm_synthetic_rubber:0 "합성 고무"
 pm_steamworks:0 "증기작업"
 pm_no_artillery_production:0 "소화기 우선 시"
 pm_artillery_production:0 "화포 생산"
 pmg_automobile_production:0 "자동차 공장"
 pm_automobile_production:0 "자동차 공장"
 pmg_restaurants:0 "레스토랑"
 pm_no_restaurants:0 "레스토랑 없음"
 pm_fish_restaurants:0 "생선 레스토랑"
 pm_meat_restaurants:0 "육류 레스토랑"
 pm_mixed_restaurants:0 "혼합 레스토랑"
 pm_luxury_restaurants:0 "럭셔리 레스토랑"