l_english:
  # DELETE:
    # pm_disabled_gin
    # pm_disabled_elastics
    # pm_masticators
    # pm_rubber_bands
    # pm_luxury_clothes

  # Agriculture Buildings
 pm_primary:0 "Primary"
 pmg_secondary_building_rye_farm:0 "Secondary"
 pmg_secondary_building_wheat_farm:0 "Secondary"
 pmg_secondary_building_rice_farm:0 "Secondary"
 pmg_secondary_building_maize_farm:0 "Secondary"
 pmg_secondary_building_millet_farm:0 "Secondary"
 pm_no_secondary:0 "Maintain Single Crop"
 pm_potatoes:0 "Potatoes"
 pm_vineyards:0 "Vineyards"
 pm_vineyards_building_maize_farm:0 "Vineyards"
 pm_apple_orchards:0 "Apple Orchards"
 pm_citrus_orchards:0 "Citrus Orchards"
 pm_fig_orchards:0 "Fig Orchards"
 pm_fig_orchards_building_rice_farm:0 "Fig Orchards"
 pm_mulberry_groves:0 "Mulberry Groves"

 pmg_automation:0 "Automation"
 pmg_automation_building_food_industry:0 "Automation"
 pmg_automation_building_textile_mills:0 "Automation"
 pmg_automation_building_furniture_manufacturies:0 "Automation"
 pmg_automation_building_tooling_workshops:0 "Automation"
 pmg_automation_building_paper_mills:0 "Automation"
 pmg_automation_building_steel_mills:0 "Automation"
 pmg_automation_building_motor_industry:0 "Automation"
 pmg_automation_building_automotive_industry: "$pmg_automation$"
 pm_civilian_priority:0 "Civilian Priority"
 pm_military_priority:0 "Military Priority"

  # Textile Mills
 pm_craftsman_sewing:0 "Craftsman Sewing"
 pm_sewing_machines:0 "Sewing Machines"
 pm_electric_sewing_machines:0 "Electric Sewing Machines"
 pm_traditional_looms:0 "Traditional Looms"
 pm_mechanized_looms:0 "Mechanized Looms"
 pm_automatic_power_looms:0 "Automatic Power Looms"

  # Glassworks
 pm_leaded_glass:0 "Leaded Glass"
 pm_manual_glassblowing:0 "Manual Glassblowing"

  # Chemical Plants
 pm_leblanc_process:0 "Leblanc Process"
 pm_no_explosives_production:0 "Prioritize Fertilizer Production"
 pm_ammonia-soda_process:0 "Ammonia-soda Process"
 pm_vacuum_evaporation:0 "Vacuum Evaporation"
 pm_brine_electrolysis:0 "Brine Electrolysis"
 pmg_fertilizer_production:0 "Fertilizer Production"
 pm_no_artificial_fertilizers:0 "No Artificial Fertilizers"
 pm_artificial_fertilizers:0 "Artificial Fertilizers"
 pm_improved_fertilizer:0 "Improved Fertilizers"
 pm_nitrogen_fixation:0 "Nitrogen Fixation Process"
 pm_dyes_production:0 "Dyes Production"
 pm_no_synthetic_dyes:0 "No Synthetic Dyes"
 pmg_synthetic_dyes:0 "Synthetic Dyes"
 pm_silk_production:0 "Silk Production"
 pm_no_artificial_fibers:0 "Prioritize Dye Production"
 pm_rayon:0 "Rayon"
 pm_synthetic_oil:0 "Synthetic Oil"
 pm_synthetic_rubber:0 "Synthetic Rubber"

  # Foundries
 pm_steamworks:0 "Steamworks"
 pm_no_artillery_production:0 "Prioritize Small Arms Production"
 pm_artillery_production:0 "Artillery Production"

  # Motor Industries
 pmg_automobile_production:0 "Automobile Production"
 pm_automobile_production:0 "Automobile Production"
 pm_mass_automobile_production: "Mass Production"

 #Restaurants
 pmg_restaurants:0 "Restaurants"
 pm_no_restaurants:0 "No Restaurants"
 pm_fish_restaurants:0 "Fish Restaurants"
 pm_meat_restaurants:0 "Meat Restaurants"
 pm_mixed_restaurants:0 "Mixed Restaurants"
 pm_luxury_restaurants:0 "Luxury Restaurants"

 #Copper mines
 pmg_mining_equipment_building_copper_mine:0 "Mining Equipment"
 pm_picks_and_shovels_building_copper_mine:0 "Picks and Shovels"
 pm_atmospheric_engine_pump_building_copper_mine:0 "Atmospheric Engine Pump"
 pm_condensing_engine_pump_building_copper_mine:0 "Condensing Engine Pump"
 pm_diesel_pump_building_copper_mine:0 "Diesel Pump"
 pmg_explosives_building_copper_mine:0 "Explosives"
 pm_nitroglycerin_building_copper_mine:0 "Nitroglycerin"
 pm_dynamite_building_copper_mine:0 "Dynamite"
 pmg_steam_automation_building_copper_mine:0 "Steam Automation"
 pmg_train_automation_building_copper_mine:0 "Train Automation"