l_simp_chinese:
 pm_primary:0 "主要"
 pmg_secondary_building_rye_farm:0 "次要"
 pmg_secondary_building_wheat_farm:0 "次要"
 pmg_secondary_building_rice_farm:0 "次要"
 pmg_secondary_building_maize_farm:0 "次要"
 pmg_secondary_building_millet_farm:0 "次要"
 pm_no_secondary:0 "维持单一作物"
 pm_potatoes:0 "马铃薯"
 pm_vineyards:0 "葡萄园"
 pm_vineyards_building_maize_farm:0 "葡萄园"
 pm_apple_orchards:0 "苹果园"
 pm_citrus_orchards:0 "柑橘园"
 pm_fig_orchards:0 "无花果园"
 pm_fig_orchards_building_rice_farm:0 "无花果园"
 pm_mulberry_groves:0 "桑树林"
 pmg_automation:0 "自动化"
 pmg_automation_building_food_industry:0 "自动化"
 pmg_automation_building_motor_industry:0 "自动化"
 pm_civilian_priority:0 "民用优先"
 pm_military_priority:0 "军用优先"
 pm_craftsman_sewing:0 "工匠缝纫"
 pm_sewing_machines:0 "缝纫机"
 pm_electric_sewing_machines:0 "电动缝纫机"
 pm_traditional_looms:0 "传统织机"
 pm_mechanized_looms:0 "机械化织机"
 pm_automatic_power_looms:0 "自动化动力织机"
 pm_leaded_glass:0 "含铅玻璃"
 pm_manual_glassblowing:0 "手工吹制玻璃"
 pm_leblanc_process:0 "勒布朗法"
 pm_no_explosives_production:0 "优先肥料生产"
 pm_ammonia-soda_process:0 "氨碱法"
 pm_vacuum_evaporation:0 "真空蒸发"
 pm_brine_electrolysis:0 "氯碱法"
 pmg_fertilizer_production:0 "肥料生产"
 pm_no_artificial_fertilizers:0 "无人工肥"
 pm_artificial_fertilizers:0 "人工肥"
 pm_improved_fertilizer:0 "改良化肥"
 pm_nitrogen_fixation:0 "固氮法"
 pm_dyes_production:0 "染料生产"
 pm_no_synthetic_dyes:0 "无合成染料"
 pmg_synthetic_dyes:0 "合成染料"
 pm_silk_production:0 "丝绸生产"
 pm_no_artificial_fibers:0 "优先染料生产"
 pm_rayon:0 "尼龙"
 pm_steamworks:0 "蒸汽作业"
 pm_no_artillery_production:0 "优先轻武器生产"
 pm_artillery_production:0 "火炮生产"
 pmg_automobile_production:0 "汽车生产"
 pm_automobile_production:0 "汽车生产"
 pm_synthetic_oil:0 "合成油"
 pm_synthetic_rubber:0 "合成橡胶"
 pmg_restaurants:0 "餐馆"
 pm_no_restaurants:0 "无餐馆"
 pm_fish_restaurants:0 "鱼类餐馆"
 pm_meat_restaurants:0 "肉类餐馆"
 pm_mixed_restaurants:0 "混合餐馆"
 pm_luxury_restaurants:0 "豪华餐馆"
 pmg_automation_building_automotive_industry: "$pmg_automation$"
 pm_mass_automobile_production: "大规模生产"
 pmg_mining_equipment_building_copper_mine:0 "采矿设备"
 pm_picks_and_shovels_building_copper_mine:0 "镐和铲"
 pm_atmospheric_engine_pump_building_copper_mine:0 "大气蒸汽机泵"
 pm_condensing_engine_pump_building_copper_mine:0 "冷凝蒸汽机泵"
 pm_diesel_pump_building_copper_mine:0 "柴油泵"
 pmg_explosives_building_copper_mine:0 "炸药"
 pm_nitroglycerin_building_copper_mine:0 "硝化甘油"
 pm_dynamite_building_copper_mine:0 "黄色炸药"
 pmg_steam_automation_building_copper_mine:0 "蒸汽自动化"
 pmg_train_automation_building_copper_mine:0 "列车自动化"
 pmg_pharmaceuticals:0 "药物"
 pm_no_pharmaceuticals:0 "无药物生产"
 pm_pharmaceuticals:0 "药物生产"
 pmg_aeroplanes:0 "飞机"
 pm_aeroplane_production:0 "飞机生产"
 pm_mass_aeroplane_production:0 "大规模飞机生产"
 pmg_television_category: "电视"
 pm_no_televisions: "优先电话生产"
 pm_cathode_tube_televisions: "电视生产"
 pm_sugar_beets: "甜菜"
 pmg_automation_building_textile_mill:0 "自动化"
 pmg_automation_building_furniture_manufactory:0 "自动化"
 pmg_automation_building_tooling_workshop:0 "自动化"
 pmg_automation_building_paper_mill:0 "自动化"
 pmg_automation_building_steel_mill:0 "自动化"